-- MySQL Script generated by MySQL Workbench
-- 05/05/15 12:10:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema alumnosnotas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `alumnosnotas` ;

-- -----------------------------------------------------
-- Schema alumnosnotas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alumnosnotas` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `alumnosnotas` ;

-- -----------------------------------------------------
-- Table `alumnosnotas`.`alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alumnosnotas`.`alumnos` ;

CREATE TABLE IF NOT EXISTS `alumnosnotas`.`alumnos` (
  `nombre` VARCHAR(60) NOT NULL,
  `dni` VARCHAR(9) NULL,
  `nota` INT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
